language: python
python: 
  - '2.7'

before_install:
- sudo apt-get update -qq
- pip install toil[all]
- pip install .
- pip install -r dev-requirements.txt

script:
  - python setup.py test
  - flake8 --ignore=E501,E722,F401,F841,W504 wfinterop/

after_success:
  - coveralls
